kind: GatewayService
name: rjv-20260317-123-dev
tags: [ns.gw-143d8.dev]
url: https://httpbun.com
protocol: https
routes:
  - name: rjv-20260317-123-dev
    tags: [ns.gw-143d8.dev]
    hosts:
      - rjv-20260317.dev.api.gov.bc.ca

