name: Deploy Configuration v3
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GW: gw-143d8
    steps:
      - uses: actions/checkout@v6

      - name: Get GWA Command Line
        run: |
          GWA_CLI_VERSION=v3.0.6; curl -L -O https://github.com/bcgov/gwa-cli/releases/download/${GWA_CLI_VERSION}/gwa_Linux_x86_64.tgz
          tar -xf gwa_Linux_x86_64.tgz

      - name: Apply Namespace
        run: |
          export PATH=`pwd`:$PATH
          cd .gwa-resource
          
          gwa login \
          --client-id=${{ secrets.GWA_ACCT_ID }} \
          --client-secret=${{ secrets.GWA_ACCT_SECRET }}
          gwa config set gateway $GW
          gwa apply -i gw-config-dev.yaml
          # gwa pg
